export type Service = {
  id: string;
  label: string;
  monthly: number;
  group: string;
};

export type Requirement =
  | "verizon"
  | "walmart_plus"
  | "tmobile"
  | "xfinity"
  | "instacart_plus"
  | "amazon_prime"
  | "att"
  | "spectrum_charter"
  | "apple_one";

export type IncludedWith =
  | "verizon"
  | "walmart_plus"
  | "tmobile"
  | "xfinity"
  | "instacart_plus"
  | "amazon_prime"
  | "att"
  | "spectrum_charter"
  | "apple_one";

export type OptionCategory =
  | "direct"
  | "bundle"
  | "carrier"
  | "membership"
  | "promo";

export type PriceStatus =
  | "current"
  | "scheduled_change"
  | "expired"
  | "needs_verification";

export type Provider =
  | "direct"
  | "verizon"
  | "walmart_plus"
  | "tmobile"
  | "xfinity"
  | "instacart_plus"
  | "apple"
  | "amazon"
  | "hulu"
  | "philo"
  | "roku";

export type Option = {
  id: string;
  name: string;
  provider: Provider;
  monthly: number;
  effectiveMonthly?: number;
  covers: string[];
  notes: string;
  source: string;
  sourceUrl?: string;
  affiliateUrl?: string;
  requires?: Requirement[];
  includedWith?: IncludedWith;
  category: OptionCategory;
  effectiveDate?: string;
  expiresAt?: string;
  introLengthMonths?: number;
  standardMonthly?: number;
  mutuallyExclusiveGroup?: string;
  lastChecked?: string;
  priceStatus?: PriceStatus;
};

/** Per-plan verification date (ISO YYYY-MM-DD). Update only options you re-checked. */
const LEGACY_LAST_CHECKED = "2026-05-02";
const VERIFIED_LAST_CHECKED = "2026-05-22";

/** Option ids verified against official sources on VERIFIED_LAST_CHECKED. */
const VERIFIED_OPTION_IDS = new Set<string>([
  "amcplus_direct",
  "apple_direct",
  "apple_one_individual",
  "apple_tv_rokt_30day_promo",
  "crunchyroll_direct",
  "directv_choice_direct",
  "directv_entertainment_direct",
  "directv_premier_direct",
  "directv_stream_5day_trial",
  "directv_stream_choice",
  "directv_stream_choice_intro",
  "directv_stream_entertainment",
  "directv_stream_entertainment_intro",
  "directv_stream_premier",
  "directv_stream_premier_intro",
  "directv_stream_ultimate",
  "directv_stream_ultimate_intro",
  "directv_ultimate_direct",
  "disney_direct",
  "disney_hulu_bundle_promo",
  "disney_hulu_max_bundle",
  "disney_hulu_max_bundle_no_ads",
  "discoveryplus_direct",
  "instacart_peacock",
  "max_direct",
  "max_standard_direct",
  "paramount_direct",
  "paramount_premium_direct",
  "peacock_apple_tv_bundle",
  "peacock_direct",
  "peacock_premium_plus_direct",
  "peacock_select_direct",
  "sling_blue_3mo_prepay",
  "sling_blue_direct",
  "sling_orange_3mo_prepay",
  "sling_orange_blue_3mo_prepay",
  "sling_orange_blue_direct",
  "sling_orange_blue_promo",
  "sling_orange_direct",
  "sling_select_3mo_prepay",
  "sling_orange_blue_sports_extra_direct",
  "sling_orange_blue_sports_extra_3mo_prepay",
  "sling_orange_blue_news_extra_direct",
  "sling_orange_blue_news_extra_3mo_prepay",
  "roku_amcplus_streaming_day_26",
  "roku_apple_tv_streaming_day_26",
  "roku_crunchyroll_streaming_day_26",
  "roku_discoveryplus_streaming_day_26",
  "roku_starz_streaming_day_26",
  "xfinity_streamsaver_peacock_netflix_max",
  "xfinity_streamsaver_peacock_netflix_disney_hulu_max",
  "xfinity_streamsaver_peacock_netflix_apple_disney_hulu_max",
  "xfinity_streamsaver_peacock_netflix_apple_max_now_tv",
  "youtube_tv_direct",
  "youtube_tv_promo",
  "youtube_tv_sports_direct",
  "youtube_tv_sports_promo",
  "tmobile_netflix_on_us",
  "tmobile_apple_tv_discount",
  "tmobile_netflix_premium_upgrade",
  "netflix_direct",
  "netflix_standard_direct",
  "netflix_premium_direct",
  "espn_select_direct",
  "espn_unlimited_direct",
  "disney_hulu_espn_unlimited_bundle",
  "hulu_direct",
  "hulu_no_ads_direct",
  "hulu_live_tv_direct",
  "hulu_live_tv_no_ads_direct",
  "hulu_live_tv_only_direct",
  "disney_hulu_bundle",
  "disney_hulu_bundle_premium",
  "disney_hulu_espn_select_bundle",
  "disney_hulu_espn_select_bundle_premium",
  "disney_hulu_espn_unlimited_bundle_premium",
  "disney_hulu_max_bundle",
  "disney_hulu_max_bundle_no_ads",
  "fubo_direct",
  "fubo_promo",
  "fubo_sports_news_direct",
  "fubo_elite_direct",
  "fubo_premier_direct",
  "fubo_latino_direct",
  "fubo_pro_promo",
  "philo_essential_direct",
  "philo_bundle_plus",
  "prime_membership_video",
  "prime_video_direct",
  "starz_direct",
  "starz_promo",
  "starz_annual_prepay",
  "verizon_disney_bundle",
  "verizon_netflix_max_current",
  "verizon_netflix_max_future",
  "walmart_paramount",
  "walmart_peacock",
]);

/** Re-spot-checked 2026-07-15; catalog prices matched official pages (scrapers not auto-applied). */
const PRICING_PASS_LAST_CHECKED = "2026-07-15";
const PRICING_PASS_VERIFIED_OPTION_IDS = new Set<string>([
  "apple_direct",
  "max_direct",
  "max_standard_direct",
  "netflix_direct",
  "disney_hulu_bundle",
  "disney_hulu_bundle_promo",
  "disney_hulu_espn_unlimited_bundle",
  "disney_hulu_max_bundle",
  "disney_hulu_bundle_premium",
  "disney_hulu_espn_select_bundle",
  "disney_hulu_espn_select_bundle_premium",
  "disney_hulu_espn_unlimited_bundle_premium",
  "disney_hulu_max_bundle_no_ads",
  "hulu_direct",
  "hulu_live_tv_direct",
  "peacock_direct",
  "peacock_select_direct",
  "peacock_premium_plus_direct",
  "philo_bundle_plus",
  "philo_essential_direct",
  "sling_blue_direct",
  "sling_orange_blue_direct",
  "sling_orange_direct",
  "sling_orange_blue_promo",
  "starz_direct",
  "youtube_tv_direct",
  "youtube_tv_promo",
  "youtube_tv_sports_direct",
  "youtube_tv_sports_promo",
  "fubo_direct",
  "fubo_sports_news_direct",
  "fubo_elite_direct",
  "fubo_latino_direct",
  "fubo_promo",
  "fubo_pro_promo",
  "fubo_premier_direct",
  "directv_entertainment_direct",
  "directv_choice_direct",
  "directv_ultimate_direct",
  "directv_premier_direct",
  "verizon_netflix_max_future",
  "verizon_disney_bundle",
  "tmobile_netflix_on_us",
  "tmobile_netflix_premium_upgrade",
  "tmobile_apple_tv_discount",
  "instacart_peacock",
  "xfinity_streamsaver_peacock_netflix_max",
  "xfinity_streamsaver_peacock_netflix_disney_hulu_max",
  "xfinity_streamsaver_peacock_netflix_apple_disney_hulu_max",
  "xfinity_streamsaver_peacock_netflix_apple_max_now_tv",
]);

function catalogLastChecked(optionId: string): string {
  if (PRICING_PASS_VERIFIED_OPTION_IDS.has(optionId)) {
    return PRICING_PASS_LAST_CHECKED;
  }
  return VERIFIED_OPTION_IDS.has(optionId)
    ? VERIFIED_LAST_CHECKED
    : LEGACY_LAST_CHECKED;
}

export const services: Service[] = [
  {
    id: "netflix",
    label: "Netflix",
    monthly: 8.99,
    group: "Netflix",
  },
  {
    id: "disney",
    label: "Disney+",
    monthly: 11.99,
    group: "Disney+",
  },
  {
    id: "hulu",
    label: "Hulu",
    monthly: 11.99,
    group: "Hulu",
  },
  {
    id: "max",
    label: "Max",
    monthly: 10.99,
    group: "Max",
  },
  {
    id: "peacock",
    label: "Peacock",
    monthly: 10.99,
    group: "Peacock",
  },
  {
    id: "paramount",
    label: "Paramount+",
    monthly: 8.99,
    group: "Paramount+",
  },
  {
    id: "apple",
    label: "Apple TV+",
    monthly: 12.99,
    group: "Apple TV+",
  },
  {
    id: "prime",
    label: "Prime Video",
    monthly: 8.99,
    group: "Prime Video",
  },
  {
    id: "espn",
    label: "ESPN+",
    monthly: 12.99,
    group: "ESPN+",
  },
  {
    id: "amcplus",
    label: "AMC+",
    monthly: 7.99,
    group: "AMC+",
  },
  {
    id: "starz",
    label: "STARZ",
    monthly: 11.99,
    group: "STARZ",
  },
  {
    id: "crunchyroll",
    label: "Crunchyroll",
    monthly: 9.99,
    group: "Crunchyroll",
  },
  {
    id: "discoveryplus",
    label: "discovery+",
    monthly: 5.99,
    group: "discovery+",
  },
  {
    id: "youtube_tv",
    label: "YouTube TV",
    monthly: 82.99,
    group: "YouTube TV",
  },
  {
    id: "hulu_live_tv",
    label: "Hulu + Live TV",
    monthly: 89.99,
    group: "Hulu + Live TV",
  },
  {
    id: "sling_tv",
    label: "Sling TV",
    monthly: 60.99,
    group: "Sling TV",
  },
  {
    id: "fubo",
    label: "Fubo",
    monthly: 88.99,
    group: "Fubo",
  },
  {
    id: "philo",
    label: "Philo",
    monthly: 25,
    group: "Philo",
  },
  {
    id: "directv",
    label: "DirecTV",
    monthly: 94.99,
    group: "DirecTV",
  },
];

export const options: Option[] = [
  // DIRECT STREAMING PLANS
  {
    id: "netflix_direct",
    name: "Netflix Standard with Ads",
    provider: "direct",
    monthly: 8.99,
    covers: ["Netflix"],
    notes:
      "Standard with ads: $8.99/mo on netflix.com/ads-plan — short ads, 1080p Full HD, 2 simultaneous streams, downloads included. Live events may contain ads.",
    source: "Netflix",
    sourceUrl: "https://www.netflix.com/ads-plan",
    category: "direct",
    mutuallyExclusiveGroup: "netflix_access",
    lastChecked: catalogLastChecked("netflix_direct"),
    priceStatus: "current",
  },
  {
    id: "netflix_standard_direct",
    name: "Netflix Standard",
    provider: "direct",
    monthly: 19.99,
    covers: ["Netflix"],
    notes:
      "Ad-free movies, TV shows, and games. 2 simultaneous streams, 1080p Full HD, downloads on 2 devices. Option to add 1 extra member (+$7.99/mo with ads or +$9.99/mo without ads). Basic plan discontinued.",
    source: "Netflix",
    sourceUrl: "https://www.netflix.com/signup",
    category: "direct",
    mutuallyExclusiveGroup: "netflix_access",
    lastChecked: catalogLastChecked("netflix_standard_direct"),
    priceStatus: "current",
  },
  {
    id: "netflix_premium_direct",
    name: "Netflix Premium",
    provider: "direct",
    monthly: 26.99,
    covers: ["Netflix"],
    notes:
      "Ad-free with 4 simultaneous streams, 4K Ultra HD + HDR where available, downloads on 6 devices. Up to 2 extra members (+$7.99/mo each with ads or +$9.99/mo each without ads).",
    source: "Netflix",
    sourceUrl: "https://www.netflix.com/signup",
    category: "direct",
    mutuallyExclusiveGroup: "netflix_access",
    lastChecked: catalogLastChecked("netflix_premium_direct"),
    priceStatus: "current",
  },
  {
    id: "disney_direct",
    name: "Disney+ (With Ads)",
    provider: "direct",
    monthly: 11.99,
    covers: ["Disney+"],
    notes:
      "Disney+ with ads; source is Disney+ commerce signup on disneyplus.com (package=disney_duo_basic)—intentional for this solo option.",
    source: "Disney+",
    sourceUrl: "https://www.disneyplus.com/commerce/cadence?package=disney_duo_basic",
    category: "direct",
    mutuallyExclusiveGroup: "disney_access",
    lastChecked: catalogLastChecked("disney_direct"),
    priceStatus: "current",
  },
  {
    id: "hulu_direct",
    name: "Hulu (With Ads)",
    provider: "direct",
    monthly: 11.99,
    covers: ["Hulu"],
    notes:
      "$11.99/mo standalone Hulu (With Ads) per hulu.com/welcome fine print (vs $12.99 Disney+ solo). Annual billing $119.99/yr also offered. Student plan $1.99/mo with verification.",
    source: "Hulu",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "direct",
    mutuallyExclusiveGroup: "hulu_access",
    lastChecked: catalogLastChecked("hulu_direct"),
    priceStatus: "current",
  },
  {
    id: "hulu_no_ads_direct",
    name: "Hulu (No Ads)",
    provider: "direct",
    monthly: 18.99,
    covers: ["Hulu"],
    notes:
      "Ad-free Hulu streaming library (live TV linear content may still include ads if bundled). Priced per Hulu help center plan table.",
    source: "Hulu",
    sourceUrl: "https://help.hulu.com/article/hulu-how-much-does-hulu-cost",
    category: "direct",
    mutuallyExclusiveGroup: "hulu_access",
    lastChecked: catalogLastChecked("hulu_no_ads_direct"),
    priceStatus: "current",
  },
  {
    id: "max_direct",
    name: "HBO Max Basic with Ads",
    provider: "direct",
    monthly: 10.99,
    covers: ["Max"],
    notes:
      "Stream on 2 devices at once in Full HD with limited ads. Live sports on select plans (e.g. NHL on TNT, MLB on TBS). Annual plan $109.99/yr (~$19 vs 12× monthly). Plan availability may vary by billing provider.",
    source: "HBO Max",
    sourceUrl: "https://www.hbomax.com/lapsed",
    category: "direct",
    mutuallyExclusiveGroup: "max_access",
    lastChecked: catalogLastChecked("max_direct"),
    priceStatus: "current",
  },
  {
    id: "max_standard_direct",
    name: "HBO Max Standard",
    provider: "direct",
    monthly: 18.49,
    covers: ["Max"],
    notes:
      "Ad-free on-demand streaming on 2 devices in Full HD; 30 downloads for offline viewing. Live sports on select plans. Annual plan $184.99/yr (~$33 vs 12× monthly). Ads may still appear on select live/linear content per HBO Max terms.",
    source: "HBO Max",
    sourceUrl: "https://www.hbomax.com/lapsed",
    category: "direct",
    mutuallyExclusiveGroup: "max_access",
    lastChecked: catalogLastChecked("max_standard_direct"),
    priceStatus: "current",
  },
  {
    id: "peacock_select_direct",
    name: "Peacock Select",
    provider: "direct",
    monthly: 7.99,
    covers: ["Peacock"],
    notes:
      "Select tier with ads: TV favorites from NBC, Bravo, and more. Excludes live sports, hit movies, and Peacock Originals. Annual $79.99/yr on peacocktv.com/plans/all-monthly.",
    source: "Peacock",
    sourceUrl: "https://www.peacocktv.com/plans/all-monthly",
    category: "direct",
    mutuallyExclusiveGroup: "peacock_access",
    lastChecked: catalogLastChecked("peacock_select_direct"),
    priceStatus: "current",
  },
  {
    id: "peacock_direct",
    name: "Peacock Premium",
    provider: "direct",
    monthly: 10.99,
    covers: ["Peacock"],
    notes:
      "Premium tier with ads (most popular on Peacock): NBC/Bravo TV favorites, live sports and events, hit films, and Peacock Originals. Annual $109.99/yr (12 months for the price of 10).",
    source: "Peacock",
    sourceUrl: "https://www.peacocktv.com/plans/all-monthly",
    category: "direct",
    mutuallyExclusiveGroup: "peacock_access",
    lastChecked: catalogLastChecked("peacock_direct"),
    priceStatus: "current",
  },
  {
    id: "peacock_premium_plus_direct",
    name: "Peacock Premium Plus",
    provider: "direct",
    monthly: 16.99,
    covers: ["Peacock"],
    notes:
      "Premium Plus: TV, movies, sports, and Originals with no ads on most on-demand (limited exclusions). Downloads and offline titles where available. Live sports/events, some shows/movies, channels, and sponsored pages may still include ads. Annual $169.99/yr (12 for 10).",
    source: "Peacock",
    sourceUrl: "https://www.peacocktv.com/plans/all-monthly",
    category: "direct",
    mutuallyExclusiveGroup: "peacock_access",
    lastChecked: catalogLastChecked("peacock_premium_plus_direct"),
    priceStatus: "current",
  },
  {
    id: "peacock_apple_tv_bundle",
    name: "Apple TV + Peacock bundle",
    provider: "apple",
    monthly: 14.99,
    covers: ["Apple TV+", "Peacock"],
    notes:
      "Peacock + Apple TV bundle starting at $14.99/mo on peacocktv.com (cancel anytime). Billed as one bundle; Peacock tier is typically Premium with ads—confirm at signup. For existing Peacock subscribers billed by Peacock, upgrade via account settings.",
    source: "Peacock",
    sourceUrl: "https://www.peacocktv.com/",
    category: "bundle",
    mutuallyExclusiveGroup: "apple_peacock_bundle_family",
    lastChecked: catalogLastChecked("peacock_apple_tv_bundle"),
    priceStatus: "current",
  },
  {
    id: "paramount_direct",
    name: "Paramount+ Essential",
    provider: "direct",
    monthly: 8.99,
    covers: ["Paramount+"],
    notes:
      "Entry plan from $8.99/mo on paramountplus.com. CBS, BET, Comedy Central, MTV, Nickelodeon, and more; live sports including NFL on CBS and UFC; stream on up to 3 devices. May include ads on live TV and some content. Student 50% discount available separately.",
    source: "Paramount+",
    sourceUrl: "https://www.paramountplus.com/",
    category: "direct",
    mutuallyExclusiveGroup: "paramount_access",
    lastChecked: catalogLastChecked("paramount_direct"),
    priceStatus: "current",
  },
  {
    id: "paramount_premium_direct",
    name: "Paramount+ Premium (with SHOWTIME)",
    provider: "direct",
    monthly: 13.99,
    covers: ["Paramount+"],
    notes:
      "Premium plan includes all of SHOWTIME ad-free (trailers and sponsorship may still appear). Downloads for offline viewing, more live sports on your local CBS station, and up to 3 simultaneous streams. Live TV channels may still include ads.",
    source: "Paramount+",
    sourceUrl: "https://www.paramountplus.com/",
    category: "direct",
    mutuallyExclusiveGroup: "paramount_access",
    lastChecked: catalogLastChecked("paramount_premium_direct"),
    priceStatus: "current",
  },
  {
    id: "apple_direct",
    name: "Apple TV+",
    provider: "direct",
    monthly: 12.99,
    covers: ["Apple TV+"],
    notes: "Standard Apple TV+ subscription.",
    source: "Apple",
    sourceUrl: "https://www.apple.com/apple-tv/",
    category: "direct",
    mutuallyExclusiveGroup: "apple_tv_access",
    lastChecked: catalogLastChecked("apple_direct"),
    priceStatus: "current",
  },
  {
    id: "prime_video_direct",
    name: "Prime Video standalone",
    provider: "direct",
    monthly: 8.99,
    covers: ["Prime Video"],
    notes: "Standalone Prime Video subscription without full Prime membership.",
    source: "Amazon",
    sourceUrl:
      "https://www.amazon.com/gp/help/customer/display.html?nodeId=G34EUPKVMYFW8N2U",
    category: "direct",
    mutuallyExclusiveGroup: "prime_video_access",
    lastChecked: catalogLastChecked("prime_video_direct"),
    priceStatus: "current",
  },
  {
    id: "espn_select_direct",
    name: "ESPN Select",
    provider: "direct",
    monthly: 12.99,
    covers: ["ESPN+"],
    notes:
      "ESPN+ only: 30,000+ live events (college, international soccer, golf, tennis, combat), ESPN Originals, 30 for 30, and more. Up to 3 simultaneous streams. Former ESPN+ subscribers map to Select. For all ESPN TV networks, choose ESPN Unlimited.",
    source: "ESPN",
    sourceUrl: "https://plus.espn.com",
    category: "direct",
    mutuallyExclusiveGroup: "espn_plus_access",
    lastChecked: catalogLastChecked("espn_select_direct"),
    priceStatus: "current",
  },
  {
    id: "espn_unlimited_direct",
    name: "ESPN Unlimited",
    provider: "direct",
    monthly: 29.99,
    covers: ["ESPN+"],
    notes:
      "All ESPN networks and ESPN+: ESPN, ESPN2, ESPNU, ESPNEWS, ESPN Deportes, SECN, ACCN, ESPN on ABC, SECN+, ACCNX, plus ESPN+ library. NFL (incl. Monday Night Football), NBA, WNBA, NHL, college football, WWE, soccer, and studio shows. Stream on up to 3 devices. Pay-TV customers (Hulu + Live TV, DIRECTV, Fubo, Spectrum, etc.) may already have Unlimited—activate at no extra cost.",
    source: "ESPN",
    sourceUrl: "https://plus.espn.com",
    category: "direct",
    mutuallyExclusiveGroup: "espn_plus_access",
    lastChecked: catalogLastChecked("espn_unlimited_direct"),
    priceStatus: "current",
  },
  {
    id: "amcplus_direct",
    name: "AMC+ Monthly with Ads",
    provider: "direct",
    monthly: 7.99,
    covers: ["AMC+"],
    notes: "Current ad-supported AMC+ plan.",
    source: "AMC+",
    sourceUrl: "https://www.amcplus.com",
    category: "direct",
    mutuallyExclusiveGroup: "amcplus_access",
    lastChecked: catalogLastChecked("amcplus_direct"),
    priceStatus: "current",
  },
  {
    id: "starz_direct",
    name: "STARZ (monthly)",
    provider: "direct",
    monthly: 11.99,
    covers: ["STARZ"],
    notes:
      "Standard month-to-month STARZ after promos end. Ad-free, offline downloads, stream on multiple devices. New/re-subscribers via starz.com may see limited-time offers instead of a free trial.",
    source: "STARZ",
    sourceUrl: "https://www.starz.com/us/en/buy",
    category: "direct",
    mutuallyExclusiveGroup: "starz_access",
    lastChecked: catalogLastChecked("starz_direct"),
    priceStatus: "current",
  },
  {
    id: "starz_annual_prepay",
    name: "STARZ (annual prepay)",
    provider: "direct",
    monthly: 2,
    standardMonthly: 11.99,
    introLengthMonths: 12,
    covers: ["STARZ"],
    notes:
      "Limited-time annual prepay: $23.99 for 12 months (~$2/mo vs $69.99/yr list). Best-deal tier on starz.com buy page. After 12 months, rolls to monthly billing at then-current rate (currently $11.99/mo plus tax) unless canceled.",
    source: "STARZ",
    sourceUrl: "https://www.starz.com/us/en/buy",
    category: "promo",
    mutuallyExclusiveGroup: "starz_access",
    lastChecked: catalogLastChecked("starz_annual_prepay"),
    priceStatus: "current",
  },
  {
    id: "crunchyroll_direct",
    name: "Crunchyroll Fan",
    provider: "direct",
    monthly: 9.99,
    covers: ["Crunchyroll"],
    notes: "Current entry-level Crunchyroll premium tier.",
    source: "Crunchyroll",
    sourceUrl: "https://www.crunchyroll.com/premium",
    category: "direct",
    mutuallyExclusiveGroup: "crunchyroll_access",
    lastChecked: catalogLastChecked("crunchyroll_direct"),
    priceStatus: "current",
  },
  {
    id: "discoveryplus_direct",
    name: "discovery+",
    provider: "direct",
    monthly: 5.99,
    covers: ["discovery+"],
    notes: "Base discovery+ plan with ads.",
    source: "discovery+",
    sourceUrl: "https://www.discoveryplus.com",
    category: "direct",
    mutuallyExclusiveGroup: "discoveryplus_access",
    lastChecked: catalogLastChecked("discoveryplus_direct"),
    priceStatus: "current",
  },

  // LIVE TV DIRECT PATHS
  {
    id: "youtube_tv_direct",
    name: "YouTube TV (100+ channels)",
    provider: "direct",
    monthly: 82.99,
    covers: ["YouTube TV"],
    notes:
      "Main YouTube TV plan: 100+ live channels, locals (ZIP-dependent), unlimited cloud DVR, multiview, 6 household accounts, 3 simultaneous streams. No annual contract or hidden fees. New users may get a 5-day trial at signup (card required).",
    source: "YouTube TV",
    sourceUrl: "https://tv.youtube.com/welcome/",
    category: "direct",
    mutuallyExclusiveGroup: "youtube_tv_access",
    lastChecked: catalogLastChecked("youtube_tv_direct"),
    priceStatus: "current",
  },
  {
    id: "youtube_tv_promo",
    name: "YouTube TV — new user promo (3 months)",
    provider: "direct",
    monthly: 67.99,
    standardMonthly: 82.99,
    introLengthMonths: 3,
    covers: ["YouTube TV"],
    notes:
      "Limited-time new-user offer: $67.99/mo for first 3 months (save $45 total vs $82.99/mo), then $82.99/mo. Same 100+ channel main plan. Offer ends August 26, 2026; terms at tv.youtube.com/welcome/.",
    source: "YouTube TV",
    sourceUrl: "https://tv.youtube.com/welcome/",
    category: "promo",
    mutuallyExclusiveGroup: "youtube_tv_access",
    expiresAt: "2026-08-26",
    lastChecked: catalogLastChecked("youtube_tv_promo"),
    priceStatus: "current",
  },
  {
    id: "youtube_tv_sports_direct",
    name: "YouTube TV Sports Plan (30+ channels)",
    provider: "direct",
    monthly: 64.99,
    covers: ["YouTube TV"],
    notes:
      "Sports-focused plan: 30+ channels for live games, sports analysis, and news plus locals (ZIP-dependent). Includes unlimited DVR, multiview, 6 accounts, and 3 streams. Lower ongoing rate than the 100+ channel main plan.",
    source: "YouTube TV",
    sourceUrl: "https://tv.youtube.com/welcome/",
    category: "direct",
    mutuallyExclusiveGroup: "youtube_tv_access",
    lastChecked: catalogLastChecked("youtube_tv_sports_direct"),
    priceStatus: "current",
  },
  {
    id: "youtube_tv_sports_promo",
    name: "YouTube TV Sports Plan — new user promo (12 months)",
    provider: "direct",
    monthly: 54.99,
    standardMonthly: 64.99,
    introLengthMonths: 12,
    covers: ["YouTube TV"],
    notes:
      "Limited-time new-user offer: $54.99/mo for first 12 months (save $120 total vs $64.99/mo), then $64.99/mo. Offer ends August 26, 2026; new users only. Terms at tv.youtube.com/welcome/.",
    source: "YouTube TV",
    sourceUrl: "https://tv.youtube.com/welcome/",
    category: "promo",
    mutuallyExclusiveGroup: "youtube_tv_access",
    expiresAt: "2026-08-26",
    lastChecked: catalogLastChecked("youtube_tv_sports_promo"),
    priceStatus: "current",
  },
  {
    id: "hulu_live_tv_direct",
    name: "Hulu + Live TV (With Ads)",
    provider: "hulu",
    monthly: 89.99,
    covers: ["Hulu + Live TV", "Hulu", "Disney+", "ESPN+"],
    notes:
      "$89.99/mo on hulu.com/welcome: Hulu (With Ads) + Live TV with 100+ channels, unlimited DVR, Disney+ (With Ads), and ESPN Unlimited (access in ESPN app). 3-day free trial for eligible new/returning subs. Stream on 2 devices (Unlimited Screens add-on +$9.99/mo).",
    source: "Hulu",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "hulu_live_tv_access",
    lastChecked: catalogLastChecked("hulu_live_tv_direct"),
    priceStatus: "current",
  },
  {
    id: "hulu_live_tv_no_ads_direct",
    name: "Hulu + Live TV (No Ads)",
    provider: "hulu",
    monthly: 99.99,
    covers: ["Hulu + Live TV", "Hulu", "Disney+", "ESPN+"],
    notes:
      "Hulu Premium + Live TV: ad-free Hulu and Disney+ on-demand libraries; live TV and ESPN Select may still include ads. Includes Disney+ Premium and ESPN Select with live channels. Unlimited DVR.",
    source: "Hulu",
    sourceUrl: "https://help.hulu.com/article/hulu-how-much-does-hulu-cost#live-tv",
    category: "bundle",
    mutuallyExclusiveGroup: "hulu_live_tv_access",
    lastChecked: catalogLastChecked("hulu_live_tv_no_ads_direct"),
    priceStatus: "current",
  },
  {
    id: "hulu_live_tv_only_direct",
    name: "Hulu Live TV Only",
    provider: "hulu",
    monthly: 88.99,
    covers: ["Hulu + Live TV"],
    notes:
      "Live TV channels only—excludes Hulu on-demand library and Disney+/ESPN Select streaming libraries. Slightly lower price than the full $89.99 bundle; most households prefer the bundle per Hulu plan comparison.",
    source: "Hulu",
    sourceUrl: "https://help.hulu.com/article/hulu-how-much-does-hulu-cost#live-tv",
    category: "bundle",
    mutuallyExclusiveGroup: "hulu_live_tv_access",
    lastChecked: catalogLastChecked("hulu_live_tv_only_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_direct",
    name: "Sling Orange (monthly)",
    provider: "direct",
    monthly: 45.99,
    covers: ["Sling TV"],
    notes:
      "Sling Orange billed monthly after any prepay term ends. One stream at a time; includes ESPN, TNT, TBS, and related channels per Sling.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/compare-plans",
    category: "direct",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_blue_direct",
    name: "Sling Blue (monthly)",
    provider: "direct",
    monthly: 45.99,
    covers: ["Sling TV"],
    notes:
      "Sling Blue billed monthly after any prepay term ends. Up to three simultaneous streams; includes FOX News, USA, NBC in select markets, etc.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/compare-plans",
    category: "direct",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_blue_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_direct",
    name: "Sling Orange & Blue (monthly)",
    provider: "direct",
    monthly: 60.99,
    covers: ["Sling TV"],
    notes:
      "50+ live channels (ESPN, NFL Network, USA, TNT, Bravo, FOX News, CNN, and more). Up to 4 simultaneous streams (1 Orange-exclusive + 3 Blue). Locals ABC/FOX/NBC in select markets; 50 hours free cloud DVR. Offer terms updated April 13, 2026 on sling.com.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "direct",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_select_3mo_prepay",
    name: "Sling Select — 3-month prepay",
    provider: "direct",
    monthly: 16.67,
    standardMonthly: 19.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $49.99 upfront for three months of Sling Select (lowest prepay on sling.com), then $19.99/mo. New customers; one per account; taxes extra. Local channels vary by market.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/prepay",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_select_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_3mo_prepay",
    name: "Sling Orange — 3-month prepay",
    provider: "direct",
    monthly: 38.33,
    standardMonthly: 45.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $114.99 upfront for three months of Sling Orange, then $45.99/mo. Limited-time prepay for new customers on the official prepay page.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/prepay",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_blue_3mo_prepay",
    name: "Sling Blue — 3-month prepay",
    provider: "direct",
    monthly: 38.33,
    standardMonthly: 45.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $114.99 upfront for three months of Sling Blue, then $45.99/mo. Limited-time prepay for new customers on the official prepay page.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/prepay",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_blue_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_3mo_prepay",
    name: "Sling Orange & Blue — 3-month prepay",
    provider: "direct",
    monthly: 53.33,
    standardMonthly: 60.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $159.99 upfront for three months of Orange & Blue, then $60.99/mo. New customers only; one per account (limited-time prepay per sling.com, updated April 13, 2026). Affiliate or partner promos may differ—confirm at checkout.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_sports_extra_direct",
    name: "Sling Orange & Blue + Sports Extra (monthly)",
    provider: "direct",
    monthly: 75.99,
    covers: ["Sling TV"],
    notes:
      "Orange & Blue ($60.99) plus Sports Extra ($15/mo add-on). Includes SEC, ACC, Big Ten, NFL RedZone, ESPNU, Golf Channel, and related sports channels per Sling. Then $75.99/mo ongoing.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "direct",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_sports_extra_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_sports_extra_3mo_prepay",
    name: "Sling Orange & Blue + Sports Extra — 3-month prepay",
    provider: "direct",
    monthly: 68.33,
    standardMonthly: 75.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $204.99 upfront for three months of Orange & Blue with Sports Extra, then $75.99/mo. New customers only; pricing from sling.com Orange & Blue page (April 13, 2026).",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_sports_extra_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_news_extra_direct",
    name: "Sling Orange & Blue + News Extra (monthly)",
    provider: "direct",
    monthly: 66.99,
    covers: ["Sling TV"],
    notes:
      "Orange & Blue ($60.99) plus News Extra ($6/mo add-on). Expanded news channel pack on top of the 50+ channel combo. Then $66.99/mo ongoing.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "direct",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_news_extra_direct"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_news_extra_3mo_prepay",
    name: "Sling Orange & Blue + News Extra — 3-month prepay",
    provider: "direct",
    monthly: 59.33,
    standardMonthly: 66.99,
    introLengthMonths: 3,
    covers: ["Sling TV"],
    notes:
      "Pay $177.99 upfront for three months of Orange & Blue with News Extra, then $66.99/mo. New customers only; pricing from sling.com Orange & Blue page (April 13, 2026).",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/service/sling-orange-and-blue",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_news_extra_3mo_prepay"),
    priceStatus: "current",
  },
  {
    id: "sling_orange_blue_promo",
    name: "Sling Orange & Blue — first month promo",
    provider: "direct",
    monthly: 29.99,
    standardMonthly: 60.99,
    introLengthMonths: 1,
    covers: ["Sling TV"],
    notes:
      "Former half-off first month for Orange & Blue. Not found on sling.com/deals or sling.com as of 2026-07-15 (page is mostly app-rendered; $29.99 promo text absent in HTML). Orange & Blue ongoing remains $60.99/mo on compare-plans. Kept for history; excluded from rankings while expired.",
    source: "Sling TV",
    sourceUrl: "https://www.sling.com/deals",
    category: "promo",
    mutuallyExclusiveGroup: "sling_tv_access",
    lastChecked: catalogLastChecked("sling_orange_blue_promo"),
    priceStatus: "expired",
  },
  {
    id: "fubo_sports_news_direct",
    name: "Fubo Sports + News",
    provider: "direct",
    monthly: 64.99,
    covers: ["Fubo"],
    notes:
      "Sports-first package (~28 channels): ABC/CBS/FOX locals in select markets, ESPN Unlimited included, World Cup coverage, news. Unlimited cloud DVR (9-month retention), up to 10 streams. No separate RSN fee called out on this tier on fubo.tv/welcome/plans.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "direct",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_sports_news_direct"),
    priceStatus: "current",
  },
  {
    id: "fubo_direct",
    name: "Fubo Pro",
    provider: "direct",
    monthly: 88.99,
    covers: ["Fubo"],
    notes:
      "Pro plan (~212 channels), unlimited cloud DVR, up to 10 streams. Includes locals, ESPN Unlimited, and major sports/entertainment. Additional regional sports fee may apply ($3.99–$16.99/mo by market) per fubo.tv/welcome/plans.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "direct",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_direct"),
    priceStatus: "current",
  },
  {
    id: "fubo_elite_direct",
    name: "Fubo Elite",
    provider: "direct",
    monthly: 98.99,
    covers: ["Fubo"],
    notes:
      "Elite (~276 channels): Pro lineup plus more sports nets and 4K. Unlimited cloud DVR, up to 10 streams. Additional regional sports fee may apply ($3.99–$16.99/mo by market) per fubo.tv/welcome/plans.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "direct",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_elite_direct"),
    priceStatus: "current",
  },
  {
    id: "fubo_premier_direct",
    name: "Fubo Premier",
    provider: "direct",
    monthly: 104.99,
    covers: ["Fubo"],
    notes:
      "Premier is no longer listed on fubo.tv/welcome/plans as of 2026-07-09 (Live TV plans shown: Pro, Elite, Latino). Marked expired so it cannot win rankings; confirm Fubo checkout if an account still has this legacy tier.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "direct",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_premier_direct"),
    priceStatus: "expired",
  },
  {
    id: "fubo_latino_direct",
    name: "Fubo Latino",
    provider: "direct",
    monthly: 19.99,
    covers: ["Fubo"],
    notes:
      "Spanish-language live TV package (~48 channels): news, sports, and entertainment. Unlimited cloud DVR; up to 2 streams. Can complement an English plan.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "direct",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_latino_direct"),
    priceStatus: "current",
  },
  {
    id: "fubo_promo",
    name: "Fubo Sports + News — first month promo",
    provider: "direct",
    monthly: 54.99,
    standardMonthly: 64.99,
    introLengthMonths: 1,
    covers: ["Fubo"],
    notes:
      "$10 off first month on Sports + News: $54.99 first month, then $64.99/mo per fubo.tv/welcome/plans. Free trial may be offered at signup. Taxes and regional restrictions may apply.",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "promo",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_promo"),
    priceStatus: "current",
  },
  {
    id: "fubo_pro_promo",
    name: "Fubo Pro — first month promo",
    provider: "direct",
    monthly: 63.99,
    standardMonthly: 88.99,
    introLengthMonths: 1,
    covers: ["Fubo"],
    notes:
      "$25 off first month on Pro: $63.99 first month, then $88.99/mo per fubo.tv/welcome/plans. Free trial may be offered. Additional regional sports fee may apply ($3.99–$16.99/mo by market).",
    source: "Fubo",
    sourceUrl: "https://www.fubo.tv/welcome/plans",
    category: "promo",
    mutuallyExclusiveGroup: "fubo_access",
    lastChecked: catalogLastChecked("fubo_pro_promo"),
    priceStatus: "current",
  },
  {
    id: "philo_essential_direct",
    name: "Philo Essential",
    provider: "direct",
    monthly: 25,
    covers: ["Philo"],
    notes:
      "Live TV Essential: 200+ live pay TV & free channels, 75,000+ on-demand titles, 1-year unlimited DVR. 7-day free trial for new subscribers. Premium add-ons (Hallmark+ $8, ALLBLK $7, MGM+ $8, Movies & More $3, STARZ $12) billed separately per philo.com/go/pricing.",
    source: "Philo",
    sourceUrl: "https://www.philo.com/go/pricing",
    category: "direct",
    mutuallyExclusiveGroup: "philo_access",
    lastChecked: catalogLastChecked("philo_essential_direct"),
    priceStatus: "current",
  },
  {
    id: "philo_bundle_plus",
    name: "Philo Bundle+",
    provider: "philo",
    monthly: 33,
    covers: ["Philo", "Max", "discovery+", "AMC+"],
    notes:
      "Everything in Essential plus HBO Max Basic with Ads, AMC+, discovery+, and All Reality. Advertised save ~$22/mo vs buying apps separately. No free trial on Bundle+ per philo.com/go/pricing.",
    source: "Philo",
    sourceUrl: "https://www.philo.com/go/pricing",
    category: "bundle",
    mutuallyExclusiveGroup: "philo_bundle_plus_family",
    lastChecked: catalogLastChecked("philo_bundle_plus"),
    priceStatus: "current",
  },
  {
    id: "directv_entertainment_direct",
    name: "DirecTV Entertainment (Signature / affiliate)",
    provider: "direct",
    monthly: 94.99,
    covers: ["DirecTV"],
    notes:
      "Aligned to Stream Entertainment with-fees list price ($94.99/mo) from directv.com/stream/stream-packages. Signature/affiliate path may still differ by ZIP and hardware (Gemini lease). No RSN fee on Entertainment.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_entertainment_direct"),
    priceStatus: "current",
  },
  {
    id: "directv_choice_direct",
    name: "DirecTV Choice (Signature / affiliate)",
    provider: "direct",
    monthly: 114.98,
    covers: ["DirecTV"],
    notes:
      "Aligned to Stream Choice with-fees list price ($114.98/mo) from directv.com/stream/stream-packages. RSN fee up to $19.99/mo and Gemini lease may apply by ZIP on Signature/affiliate checkout.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_choice_direct"),
    priceStatus: "current",
  },
  {
    id: "directv_ultimate_direct",
    name: "DirecTV Ultimate (Signature / affiliate)",
    provider: "direct",
    monthly: 139.98,
    covers: ["DirecTV"],
    notes:
      "Aligned to Stream Ultimate with-fees list price ($139.98/mo) from directv.com/stream/stream-packages. RSN fee up to $19.99/mo may apply; confirm Signature/affiliate checkout for your address.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_ultimate_direct"),
    priceStatus: "current",
  },
  {
    id: "directv_premier_direct",
    name: "DirecTV Premier (Signature / affiliate)",
    provider: "direct",
    monthly: 179.98,
    covers: ["DirecTV"],
    notes:
      "Aligned to Stream Premier with-fees list price ($179.98/mo) from directv.com/stream/stream-packages. Includes premium movie nets on Stream; Signature/affiliate promos and RSN/Gemini fees may differ by ZIP.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_premier_direct"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_5day_trial",
    name: "DirecTV Stream — 5-day free trial (new customers)",
    provider: "direct",
    monthly: 0,
    effectiveMonthly: 0,
    standardMonthly: 94.99,
    introLengthMonths: 1,
    covers: ["DirecTV"],
    notes:
      "Streaming App Only: 5-day free trial for new residential customers on directv.com/stream (card hold during trial). Then billed at your chosen package rate with required fees. Modeled as $0 for the first month in comparisons; actual trial is 5 days.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "promo",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_5day_trial"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_entertainment_intro",
    name: "DirecTV Entertainment intro (Stream app only)",
    provider: "direct",
    monthly: 84.99,
    standardMonthly: 94.99,
    introLengthMonths: 1,
    covers: ["DirecTV"],
    notes:
      "Advertised intro price on stream-packages before required fees; ongoing Entertainment with fees is $94.99/mo ($5 off for 24 months). No RSN fee on Entertainment. App-only, no satellite dish.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "promo",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_entertainment_intro"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_entertainment",
    name: "DirecTV Entertainment (Stream app only)",
    provider: "direct",
    monthly: 94.99,
    covers: ["DirecTV"],
    notes:
      "Streaming App Only ongoing rate with required fees—90+ channels. $5 off for 24 months on new accounts. No regional sports fee on Entertainment. Optional $10/mo Gemini device lease if you add hardware.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_entertainment"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_choice_intro",
    name: "DirecTV Choice intro (Stream app only)",
    provider: "direct",
    monthly: 84.99,
    standardMonthly: 114.98,
    introLengthMonths: 1,
    covers: ["DirecTV"],
    notes:
      "Intro price shown on stream-packages ($84.99/mo before fees); ongoing Choice with required fees is $114.98/mo ($10 off for 24 months). RSN fee up to $19.99/mo may apply by ZIP.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "promo",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_choice_intro"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_choice",
    name: "DirecTV Choice (Stream app only)",
    provider: "direct",
    monthly: 114.98,
    covers: ["DirecTV"],
    notes:
      "Streaming App Only Choice tier—125+ channels. Ongoing price with required fees; $10 off for 24 months. Regional sports fee up to $19.99/mo may apply by ZIP. Unlimited cloud DVR included.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_choice"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_ultimate_intro",
    name: "DirecTV Ultimate intro (Stream app only)",
    provider: "direct",
    monthly: 109.99,
    standardMonthly: 139.98,
    introLengthMonths: 1,
    covers: ["DirecTV"],
    notes:
      "Intro price on stream-packages; ongoing Ultimate with required fees is $139.98/mo ($15 off for 24 months). RSN fee up to $19.99/mo may apply.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "promo",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_ultimate_intro"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_ultimate",
    name: "DirecTV Ultimate (Stream app only)",
    provider: "direct",
    monthly: 139.98,
    covers: ["DirecTV"],
    notes:
      "Streaming App Only Ultimate—160+ channels. Ongoing rate with required fees; $15 off for 24 months. RSN fee up to $19.99/mo may apply.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_ultimate"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_premier_intro",
    name: "DirecTV Premier intro (Stream app only)",
    provider: "direct",
    monthly: 149.99,
    standardMonthly: 179.98,
    introLengthMonths: 1,
    covers: ["DirecTV"],
    notes:
      "Intro price on stream-packages; ongoing Premier with required fees is $179.98/mo ($20 off for 24 months). RSN fee up to $19.99/mo may apply.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "promo",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_premier_intro"),
    priceStatus: "current",
  },
  {
    id: "directv_stream_premier",
    name: "DirecTV Premier (Stream app only)",
    provider: "direct",
    monthly: 179.98,
    covers: ["DirecTV"],
    notes:
      "Streaming App Only Premier—185+ channels including premium movie networks. Ongoing rate with required fees; $20 off for 24 months. RSN fee may apply. Taxes extra; cancel anytime.",
    source: "DirecTV",
    sourceUrl: "https://www.directv.com/stream/stream-packages/",
    affiliateUrl:
      "https://www.directv.com/stream/stream-packages/?cjdata=MXxOfDB8WXww&utm_medium=Affiliate&utm_source=5370367&utm_campaign=Premium&utm_audience=Prospect&utm_creative=Skimlinks&cjevent=399a71f655ec11f181be00bb0a82b824&utm_content=Skimlinks+DIRECTV+App+Only+Free+Trial+Default+Link",
    category: "direct",
    mutuallyExclusiveGroup: "directv_access",
    lastChecked: catalogLastChecked("directv_stream_premier"),
    priceStatus: "current",
  },

  // MEMBERSHIP / INCLUDED PATHS
  {
    id: "prime_membership_video",
    name: "Prime Video included with Amazon Prime",
    provider: "amazon",
    monthly: 8.99,
    effectiveMonthly: 0,
    covers: ["Prime Video"],
    notes:
      "Prime Video is included with Amazon Prime at no extra streaming cost. Membership cost is not included in this comparison.",
    source: "Amazon Prime",
    sourceUrl: "https://www.amazon.com/amazonprime",
    requires: ["amazon_prime"],
    includedWith: "amazon_prime",
    category: "membership",
    mutuallyExclusiveGroup: "prime_video_access",
    lastChecked: catalogLastChecked("prime_membership_video"),
    priceStatus: "current",
  },
  {
    id: "apple_one_individual",
    name: "Apple TV+ included with Apple One",
    provider: "apple",
    monthly: 12.99,
    effectiveMonthly: 0,
    covers: ["Apple TV+"],
    notes:
      "Apple TV+ is included with Apple One at no extra streaming cost. Membership cost is not included in this comparison.",
    source: "Apple One",
    sourceUrl: "https://www.apple.com/apple-one/",
    requires: ["apple_one"],
    includedWith: "apple_one",
    category: "membership",
    mutuallyExclusiveGroup: "apple_tv_access",
    lastChecked: catalogLastChecked("apple_one_individual"),
    priceStatus: "current",
  },
  {
    id: "instacart_peacock",
    name: "Peacock Premium included with Instacart+",
    provider: "instacart_plus",
    monthly: 0,
    effectiveMonthly: 0,
    covers: ["Peacock"],
    notes:
      "Peacock Premium is included with Instacart+ (Instacart lists Peacock at about $109.99/year value). Membership cost is not included in this comparison. Confirmed on instacart.com/instacart-plus (2026-07-15).",
    source: "Instacart+",
    sourceUrl: "https://www.instacart.com/instacart-plus",
    requires: ["instacart_plus"],
    includedWith: "instacart_plus",
    category: "carrier",
    mutuallyExclusiveGroup: "peacock_access",
    lastChecked: catalogLastChecked("instacart_peacock"),
    priceStatus: "current",
  },
  {
    id: "walmart_paramount",
    name: "Paramount+ Essential included with Walmart+",
    provider: "walmart_plus",
    monthly: 8.99,
    effectiveMonthly: 0,
    covers: ["Paramount+"],
    notes:
      "Walmart+ members can choose Paramount+ Essential at no extra streaming cost. Automated fetch of Walmart+ help/plus pages returned blocked/junk HTML on 2026-07-15 — prices need manual confirmation.",
    source: "Walmart+",
    sourceUrl:
      "https://www.walmart.com/help/article/walmart-benefits-streaming-services/35624ec8e133496ab647a398a90cf779",
    requires: ["walmart_plus"],
    includedWith: "walmart_plus",
    category: "membership",
    mutuallyExclusiveGroup: "walmart_streaming_choice",
    lastChecked: catalogLastChecked("walmart_paramount"),
    priceStatus: "needs_verification",
  },
  {
    id: "walmart_peacock",
    name: "Peacock Premium included with Walmart+",
    provider: "walmart_plus",
    monthly: 10.99,
    effectiveMonthly: 0,
    covers: ["Peacock"],
    notes:
      "Walmart+ members can choose Peacock Premium with ads at no extra streaming cost. Only one Walmart+ streaming benefit can be active at a time. Automated fetch of Walmart+ help/plus pages returned blocked/junk HTML on 2026-07-15 — prices need manual confirmation.",
    source: "Walmart+",
    sourceUrl:
      "https://www.walmart.com/help/article/walmart-benefits-streaming-services/35624ec8e133496ab647a398a90cf779",
    requires: ["walmart_plus"],
    includedWith: "walmart_plus",
    category: "membership",
    mutuallyExclusiveGroup: "walmart_streaming_choice",
    lastChecked: catalogLastChecked("walmart_peacock"),
    priceStatus: "needs_verification",
  },

  // CORE BUNDLES
  {
    id: "disney_hulu_bundle",
    name: "Disney+, Hulu Bundle (With Ads)",
    provider: "hulu",
    monthly: 12.99,
    covers: ["Disney+", "Hulu"],
    notes:
      "$12.99/mo on hulu.com/welcome for Disney+ (With Ads) + Hulu (With Ads). Intro offers vary (e.g. $9.99 first month per Hulu terms). Select Hulu titles stream on Disney+; full Hulu library remains in Hulu app.",
    source: "Disney / Hulu",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_family",
    lastChecked: catalogLastChecked("disney_hulu_bundle"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_bundle_premium",
    name: "Disney+, Hulu Bundle (No Ads)",
    provider: "hulu",
    monthly: 19.99,
    covers: ["Disney+", "Hulu"],
    notes:
      "$19.99/mo on hulu.com/welcome: Disney+ (No Ads) and Hulu (No Ads) on-demand. Ads may still appear in select live/linear content per Disney terms.",
    source: "Disney / Hulu",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_family",
    lastChecked: catalogLastChecked("disney_hulu_bundle_premium"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_espn_select_bundle",
    name: "Disney+, Hulu, ESPN Select Bundle",
    provider: "hulu",
    monthly: 19.99,
    covers: ["Disney+", "Hulu", "ESPN+"],
    notes:
      "$19.99/mo on hulu.com/welcome with Hulu (With Ads): Disney+, Hulu, and ESPN Select. Access each service separately.",
    source: "Disney / Hulu / ESPN",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_espn_family",
    lastChecked: catalogLastChecked("disney_hulu_espn_select_bundle"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_espn_select_bundle_premium",
    name: "Disney+, Hulu, ESPN Select Bundle (No Ads)",
    provider: "hulu",
    monthly: 29.99,
    covers: ["Disney+", "Hulu", "ESPN+"],
    notes:
      "$29.99/mo on hulu.com/welcome with Hulu (No Ads): ad-free Disney+ and Hulu plus ESPN Select. Live/linear sports may still include ads.",
    source: "Disney / Hulu / ESPN",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_espn_family",
    lastChecked: catalogLastChecked("disney_hulu_espn_select_bundle_premium"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_espn_unlimited_bundle",
    name: "Disney+, Hulu, ESPN Unlimited Bundle",
    provider: "hulu",
    monthly: 35.99,
    covers: ["Disney+", "Hulu", "ESPN+"],
    notes:
      "$35.99/mo on hulu.com/welcome: Disney+ (With Ads), Hulu (With Ads), and ESPN Unlimited (all ESPN networks + ESPN+). NFL, college football, NBA, NHL, originals, and Disney+/Hulu libraries.",
    source: "Disney / Hulu / ESPN",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_espn_family",
    lastChecked: catalogLastChecked("disney_hulu_espn_unlimited_bundle"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_espn_unlimited_bundle_premium",
    name: "Disney+, Hulu, ESPN Unlimited Bundle (No Ads)",
    provider: "hulu",
    monthly: 44.99,
    covers: ["Disney+", "Hulu", "ESPN+"],
    notes:
      "$44.99/mo on hulu.com/welcome: Disney+ (No Ads), Hulu (No Ads), and ESPN Unlimited (With Ads). All ESPN networks plus Disney+/Hulu libraries.",
    source: "Disney / Hulu / ESPN",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_espn_family",
    lastChecked: catalogLastChecked("disney_hulu_espn_unlimited_bundle_premium"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_max_bundle",
    name: "Disney+, Hulu, HBO Max Bundle (With Ads)",
    provider: "hulu",
    monthly: 19.99,
    covers: ["Disney+", "Hulu", "Max"],
    notes:
      "$19.99/mo on hulu.com/welcome for Disney+, Hulu, HBO Max Bundle (With Ads). Advertised ~41–42% savings vs buying standalone. Access each app separately. U.S. only, 18+.",
    source: "Disney / Hulu / Max",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_max_family",
    lastChecked: catalogLastChecked("disney_hulu_max_bundle"),
    priceStatus: "current",
  },
  {
    id: "disney_hulu_max_bundle_no_ads",
    name: "Disney+, Hulu, HBO Max Bundle (No Ads)",
    provider: "hulu",
    monthly: 32.99,
    covers: ["Disney+", "Hulu", "Max"],
    notes:
      "Ad-free Disney+, Hulu, and HBO Max bundle. Advertised savings vs $56.47/mo standalone retail (~41% off). Ads may still appear in select live and linear content. ESPN Unlimited add-on available on the same signup page.",
    source: "Hulu",
    sourceUrl: "https://help.hulu.com/article/hulu-how-much-does-hulu-cost",
    category: "bundle",
    mutuallyExclusiveGroup: "disney_hulu_max_family",
    lastChecked: catalogLastChecked("disney_hulu_max_bundle_no_ads"),
    priceStatus: "current",
  },

  // ROKU PROMOS (Phase 1)
  // Alternate signup paths via Roku / The Roku Channel for services users already select
  // (Hulu, STARZ, etc.). No "Roku" service card. Id prefix: roku_<service>_<deal>.
  // See docs/pricing-data-process.md § Roku deals.
  {
    id: "roku_amcplus_streaming_day_26",
    name: "AMC+ — Roku Streaming Day 2026",
    provider: "roku",
    monthly: 1.99,
    standardMonthly: 7.99,
    introLengthMonths: 2,
    covers: ["AMC+"],
    notes:
      "Roku Streaming Day (May 15–25, 2026): $1.99/mo for 2 months via Premium Subscriptions on The Roku Channel, then standard AMC+ rate. US only; redeem on a Roku device. New/eligible subs per Roku terms.",
    source: "Roku",
    sourceUrl:
      "https://therokuchannel.roku.com/browse/w.LewpyBv9QLf8QoxavlrZH2y175zoj8TK9KJbw8RWs0PaVBqNv5CrgdPlVGalta9BvrB8gmikvv3kVGbJc4AjPZ1jVriK31ZDwDJefDGbeQqgMpCmzBKegpZwIe9k6YD00JIyz5eq/amc",
    category: "promo",
    effectiveDate: "2026-05-15",
    expiresAt: "2026-05-25",
    mutuallyExclusiveGroup: "amcplus_access",
    lastChecked: catalogLastChecked("roku_amcplus_streaming_day_26"),
    priceStatus: "current",
  },
  {
    id: "roku_apple_tv_streaming_day_26",
    name: "Apple TV+ — Roku Streaming Day 2026",
    provider: "roku",
    monthly: 5.99,
    standardMonthly: 12.99,
    introLengthMonths: 2,
    covers: ["Apple TV+"],
    notes:
      "Listed as “Apple TV” on Roku’s Streaming Day page: $5.99/mo for 2 months through The Roku Channel, then regular Apple TV+ monthly billing. US Roku device required during offer window.",
    source: "Roku",
    sourceUrl:
      "https://therokuchannel.roku.com/browse/w.xdGNYBW4w8hPd97D31aLsLJvepwgM5fvBvlxe57Mh0vA69wlD3CAR9gG6wPGCGdY2jY1e8Hv22JvxkM1iZ7dA3emApuDLQzlPlRmf924kd0zjpU7V9GdQ2oZCV1oZvBGGbC0xGP1/apple-tv",
    category: "promo",
    effectiveDate: "2026-05-15",
    expiresAt: "2026-05-25",
    mutuallyExclusiveGroup: "apple_tv_access",
    lastChecked: catalogLastChecked("roku_apple_tv_streaming_day_26"),
    priceStatus: "current",
  },
  {
    id: "roku_crunchyroll_streaming_day_26",
    name: "Crunchyroll — Roku Streaming Day 2026",
    provider: "roku",
    monthly: 1.99,
    standardMonthly: 9.99,
    introLengthMonths: 2,
    covers: ["Crunchyroll"],
    notes:
      "Roku Streaming Day: $1.99/mo for 2 months via The Roku Channel or Roku-managed Crunchyroll signup. Tier on Roku may differ from direct crunchyroll.com Fan plan—confirm in checkout.",
    source: "Roku",
    sourceUrl:
      "https://therokuchannel.roku.com/browse/w.r2BADo4GwMFGV4ekdKLpiPNALm0exvIVrV4bopyYUoRl7zV2QZtwMm2Aq3lAC9ylqVlDjkc5GGk5NZa4cx3r9Z6Q5lIVQejlxmW2UJR3dQoN3RsG21W3JJgBHw91m73APAFzN6W6LDaPCDb/crunchyroll",
    category: "promo",
    effectiveDate: "2026-05-15",
    expiresAt: "2026-05-25",
    mutuallyExclusiveGroup: "crunchyroll_access",
    lastChecked: catalogLastChecked("roku_crunchyroll_streaming_day_26"),
    priceStatus: "current",
  },
  {
    id: "roku_discoveryplus_streaming_day_26",
    name: "discovery+ — Roku Streaming Day 2026",
    provider: "roku",
    monthly: 2.99,
    standardMonthly: 5.99,
    introLengthMonths: 3,
    covers: ["discovery+"],
    notes:
      "Roku Streaming Day: $2.99/mo for 3 months on The Roku Channel, then standard discovery+ monthly rate. Offer window May 15–25, 2026; US Roku device.",
    source: "Roku",
    sourceUrl:
      "https://therokuchannel.roku.com/browse/w.wBG0ZdW46btY169yjMrptWqo9b48LYIYVYQy6owLCb2PRBNqVzIPg6GJvjYJUJapQzp5ZkcNwwPNJ1x7FjBgrb7W5ZcPRL8QkLraiorMlD6DzJcvy305j94WfVKjGrMqJocAgLyVWGG2Ub0xRg/discovery",
    category: "promo",
    effectiveDate: "2026-05-15",
    expiresAt: "2026-05-25",
    mutuallyExclusiveGroup: "discoveryplus_access",
    lastChecked: catalogLastChecked("roku_discoveryplus_streaming_day_26"),
    priceStatus: "current",
  },
  {
    id: "roku_starz_streaming_day_26",
    name: "STARZ — Roku Streaming Day 2026",
    provider: "roku",
    monthly: 1.99,
    standardMonthly: 11.99,
    introLengthMonths: 2,
    covers: ["STARZ"],
    notes:
      "Roku Streaming Day: $1.99/mo for 2 months via The Roku Channel, then standard STARZ monthly rate. Same offer window as roku.com/blog/streaming-day-26 (May 15–25, 2026).",
    source: "Roku",
    sourceUrl:
      "https://therokuchannel.roku.com/browse/w.9wKL8Dq0JasxW5r18Zq9SVD2b8pZqjCl0lwradoGfwqjy25keWs24aAG8dYGi8kQZpQBA0fBmmJBkwJyFv3NlbgNzduZAJGMyrJAtjlGP6LLm5hPYrM36d9dH9pqrqeWvKfYQ/starz",
    category: "promo",
    effectiveDate: "2026-05-15",
    expiresAt: "2026-05-25",
    mutuallyExclusiveGroup: "starz_access",
    lastChecked: catalogLastChecked("roku_starz_streaming_day_26"),
    priceStatus: "current",
  },

  // PROMOS
  {
    id: "disney_hulu_bundle_promo",
    name: "Disney+, Hulu Bundle — $9.99/mo (1 month)",
    provider: "hulu",
    monthly: 9.99,
    standardMonthly: 12.99,
    introLengthMonths: 1,
    covers: ["Disney+", "Hulu"],
    notes:
      "Expired intro: Hulu previously advertised $9.99 for the first month then $12.99/mo. Offer terms ended 2026-02-17. Ongoing Disney+, Hulu Bundle remains $12.99/mo (disney_hulu_bundle). Excluded from rankings.",
    source: "Disney / Hulu",
    sourceUrl: "https://www.hulu.com/welcome",
    category: "promo",
    expiresAt: "2026-02-17",
    mutuallyExclusiveGroup: "disney_hulu_family",
    lastChecked: catalogLastChecked("disney_hulu_bundle_promo"),
    priceStatus: "expired",
  },
  {
    id: "starz_promo",
    name: "STARZ — 75% off monthly (3 months)",
    provider: "direct",
    monthly: 2.99,
    standardMonthly: 11.99,
    introLengthMonths: 3,
    covers: ["STARZ"],
    notes:
      "Limited-time monthly on starz.com: $2.99/mo for 3 months (75% off $11.99), then $11.99/mo plus tax. Offer for new and returning STARZ App subscribers via starz.com; does not include a free trial. Non-refundable subscription fee.",
    source: "STARZ",
    sourceUrl: "https://www.starz.com/us/en/buy",
    category: "promo",
    mutuallyExclusiveGroup: "starz_access",
    lastChecked: catalogLastChecked("starz_promo"),
    priceStatus: "current",
  },
  {
    id: "apple_tv_rokt_30day_promo",
    name: "Apple TV+ — 30 days free (promo code)",
    provider: "apple",
    monthly: 0,
    effectiveMonthly: 0,
    standardMonthly: 12.99,
    introLengthMonths: 1,
    covers: ["Apple TV+"],
    notes:
      "Redeem at the linked Apple offer page: 30 days free, then $12.99/mo until canceled. New and qualified returning subscribers only; US only. Promotional code expires January 7, 2027. Requires Apple ID with payment method on file. Cannot be combined with other offers for the same Apple TV service.",
    source: "Apple",
    sourceUrl: "https://redeem.services.apple/roktappletv-amr-v2",
    category: "promo",
    expiresAt: "2027-01-07",
    mutuallyExclusiveGroup: "apple_tv_access",
    lastChecked: catalogLastChecked("apple_tv_rokt_30day_promo"),
    priceStatus: "current",
  },

  // CARRIER / TELECOM PERKS
  {
    id: "verizon_netflix_max_current",
    name: "Verizon Netflix + Max perk",
    provider: "verizon",
    monthly: 10,
    covers: ["Netflix", "Max"],
    notes:
      "Expired legacy Verizon Netflix + Max perk price ($10/mo). Replaced by the $13/mo rate effective May 6, 2026 (confirmed 2026-07-15).",
    source: "Verizon",
    sourceUrl: "https://www.verizon.com/support/netflix-max-perk-faqs/",
    requires: ["verizon"],
    includedWith: "verizon",
    category: "carrier",
    effectiveDate: "2026-04-05",
    expiresAt: "2026-05-05",
    mutuallyExclusiveGroup: "verizon_netflix_max_family",
    lastChecked: catalogLastChecked("verizon_netflix_max_current"),
    priceStatus: "expired",
  },
  {
    id: "verizon_netflix_max_future",
    name: "Verizon Netflix + Max perk",
    provider: "verizon",
    monthly: 13,
    covers: ["Netflix", "Max"],
    notes:
      "Current Verizon Netflix + Max perk at $13/mo (effective May 6, 2026). Confirmed on Verizon FAQs 2026-07-15.",
    source: "Verizon",
    sourceUrl: "https://www.verizon.com/support/netflix-max-perk-faqs/",
    requires: ["verizon"],
    includedWith: "verizon",
    category: "carrier",
    effectiveDate: "2026-05-06",
    mutuallyExclusiveGroup: "verizon_netflix_max_family",
    lastChecked: catalogLastChecked("verizon_netflix_max_future"),
    priceStatus: "current",
  },
  {
    id: "verizon_disney_bundle",
    name: "Verizon Disney+, Hulu, ESPN+ perk",
    provider: "verizon",
    monthly: 10,
    covers: ["Disney+", "Hulu", "ESPN+"],
    notes:
      "Verizon perk includes Disney+, Hulu, and ESPN+ with ads on eligible plans at $10/mo. Confirmed on Verizon FAQs 2026-07-15.",
    source: "Verizon",
    sourceUrl: "https://www.verizon.com/support/disney-bundle-perk-faqs/",
    requires: ["verizon"],
    includedWith: "verizon",
    category: "carrier",
    mutuallyExclusiveGroup: "verizon_disney_family",
    lastChecked: catalogLastChecked("verizon_disney_bundle"),
    priceStatus: "current",
  },
  {
    id: "tmobile_netflix_on_us",
    name: "T-Mobile Netflix Standard with Ads (On Us)",
    provider: "tmobile",
    monthly: 8.99,
    effectiveMonthly: 0,
    covers: ["Netflix"],
    notes:
      "Netflix Standard with ads (valued up to $8.99/mo) at no extra streaming cost while you keep a qualifying line in good standing. Eligible: Experience More, Experience Beyond, Go5G Next, Go5G Plus, or Magenta MAX (1+ line); or any Go5G or Magenta plan with 2+ voice lines (incl. Military, 55+, First Responder). Activate in T-Life: Manage → See plans → Manage add-ons → Netflix. One offer per T-Mobile account; existing Netflix may take 1–2 bill cycles to move billing. Confirmed 2026-07-15.",
    source: "T-Mobile",
    sourceUrl: "https://www.t-mobile.com/tv-streaming/netflix-on-us",
    requires: ["tmobile"],
    includedWith: "tmobile",
    category: "carrier",
    mutuallyExclusiveGroup: "netflix_access",
    lastChecked: catalogLastChecked("tmobile_netflix_on_us"),
    priceStatus: "current",
  },
  {
    id: "tmobile_netflix_premium_upgrade",
    name: "T-Mobile Netflix Premium upgrade",
    provider: "tmobile",
    monthly: 20,
    covers: ["Netflix"],
    notes:
      "For eligible Netflix On Us customers: upgrade to Netflix Premium billed through T-Mobile at a discounted $20/mo (up to 4 streams in one household). Requires qualifying T-Mobile plan and activation of the Netflix benefit first. Alternative discounts may apply toward other Netflix tiers; confirm in T-Life or at checkout. Confirmed 2026-07-15.",
    source: "T-Mobile",
    sourceUrl: "https://www.t-mobile.com/tv-streaming/netflix-on-us",
    requires: ["tmobile"],
    includedWith: "tmobile",
    category: "carrier",
    mutuallyExclusiveGroup: "netflix_access",
    lastChecked: catalogLastChecked("tmobile_netflix_premium_upgrade"),
    priceStatus: "current",
  },
  {
    id: "tmobile_apple_tv_discount",
    name: "T-Mobile Apple TV benefit",
    provider: "tmobile",
    monthly: 3,
    covers: ["Apple TV+"],
    notes:
      "Eligible T-Mobile plans can get Apple TV billed through T-Mobile for $3/month. Confirmed 2026-07-15.",
    source: "T-Mobile",
    sourceUrl: "https://www.t-mobile.com/tv-streaming/apple-tv-plus-deal/faq",
    requires: ["tmobile"],
    includedWith: "tmobile",
    category: "carrier",
    mutuallyExclusiveGroup: "apple_tv_access",
    lastChecked: catalogLastChecked("tmobile_apple_tv_discount"),
    priceStatus: "current",
  },
  {
    id: "xfinity_streamsaver_peacock_netflix_max",
    name: "Xfinity StreamSaver: Peacock, Netflix, HBO Max",
    provider: "xfinity",
    monthly: 22,
    covers: ["Peacock", "Netflix", "Max"],
    notes:
      "StreamStore bundle (~29% vs $30.97/mo retail). Requires Xfinity Internet or TV; check “I have Xfinity.” Peacock Premium with ads included. Use same email at activation to keep profiles. Confirmed via Xfinity StreamStore screenshot 2026-07-15.",
    source: "Xfinity StreamStore",
    sourceUrl: "https://www.xfinity.com/learn/digital-cable-tv/streaming-services",
    requires: ["xfinity"],
    includedWith: "xfinity",
    category: "carrier",
    mutuallyExclusiveGroup: "xfinity_streamsaver_family",
    lastChecked: catalogLastChecked("xfinity_streamsaver_peacock_netflix_max"),
    priceStatus: "current",
  },
  {
    id: "xfinity_streamsaver_peacock_netflix_disney_hulu_max",
    name: "Xfinity StreamSaver: Peacock, Netflix, Disney+, Hulu, HBO Max",
    provider: "xfinity",
    monthly: 30,
    covers: ["Peacock", "Netflix", "Disney+", "Hulu", "Max"],
    notes:
      "StreamStore bundle (~32% vs $43.96/mo retail). Disney+, Hulu Bundle tier as sold by Xfinity. May need to cancel separate Disney/Hulu subs to avoid duplicate billing. Confirmed via Xfinity StreamStore screenshot 2026-07-15.",
    source: "Xfinity StreamStore",
    sourceUrl: "https://www.xfinity.com/learn/digital-cable-tv/streaming-services",
    requires: ["xfinity"],
    includedWith: "xfinity",
    category: "carrier",
    mutuallyExclusiveGroup: "xfinity_streamsaver_family",
    lastChecked: catalogLastChecked("xfinity_streamsaver_peacock_netflix_disney_hulu_max"),
    priceStatus: "current",
  },
  {
    id: "xfinity_streamsaver_peacock_netflix_apple_disney_hulu_max",
    name: "Xfinity StreamSaver: Peacock, Netflix, Apple TV+, Disney+, Hulu, HBO Max",
    provider: "xfinity",
    monthly: 35,
    covers: ["Peacock", "Netflix", "Apple TV+", "Disney+", "Hulu", "Max"],
    notes:
      "StreamStore bundle (~39% vs $56.95/mo retail). Includes Apple TV+ and Disney+, Hulu Bundle. Activation fee waiver for first 4K stream box with streaming sub (Apple TV exception per Xfinity). Confirmed via Xfinity StreamStore screenshot 2026-07-15.",
    source: "Xfinity StreamStore",
    sourceUrl: "https://www.xfinity.com/learn/digital-cable-tv/streaming-services",
    requires: ["xfinity"],
    includedWith: "xfinity",
    category: "carrier",
    mutuallyExclusiveGroup: "xfinity_streamsaver_family",
    lastChecked: catalogLastChecked("xfinity_streamsaver_peacock_netflix_apple_disney_hulu_max"),
    priceStatus: "current",
  },
  {
    id: "xfinity_streamsaver_peacock_netflix_apple_max_now_tv",
    name: "Xfinity StreamSaver: Peacock, Netflix, Apple TV+, HBO Max, NOW TV",
    provider: "xfinity",
    monthly: 35,
    covers: ["Peacock", "Netflix", "Apple TV+", "Max"],
    notes:
      "StreamStore bundle at $35/mo also includes NOW TV (270+ live channels + Peacock Premium with ads per Xfinity). NOW TV is not a separate StreamWise service tile—value is in the bundle price. Confirm channels for your address. Confirmed via Xfinity StreamStore screenshot 2026-07-15.",
    source: "Xfinity StreamStore",
    sourceUrl: "https://www.xfinity.com/learn/digital-cable-tv/streaming-services",
    requires: ["xfinity"],
    includedWith: "xfinity",
    category: "carrier",
    mutuallyExclusiveGroup: "xfinity_streamsaver_family",
    lastChecked: catalogLastChecked("xfinity_streamsaver_peacock_netflix_apple_max_now_tv"),
    priceStatus: "current",
  },
];

export const defaultSelectedServices: string[] = [
  "Netflix",
  "Disney+",
  "Hulu",
];
